<?php
/**
 * Created by PhpStorm.
 * User: Netbase
 * Date: 4/23/2019
 * Time: 9:37 AM
 */


class KPI_Detail_View extends Accounts_Detail_View {

    function __construct() {
        $this->exposeMethod('showModuleDetailView');
        parent::__construct();
    }

    function preProcess(Vtiger_Request $request, $display = true)
    {
        parent::preProcess($request, $display); // TODO: Change the autogenerated stub
    }

    function process(Vtiger_Request $request)
    {
        $recordId = $request->get('record');
        $kpiModel = Vtiger_Record_Model::getInstanceById($recordId,'KPI');
        $target = $kpiModel->get('cf_01');
        $actual = $kpiModel->get('cf_02');
        $ranking_value = (($actual/$target)*100-100);

        if($ranking_value >= 10){
            $default_ranking = 'Vượt yêu cầu';
        }else if($ranking_value >= 0){
            $default_ranking ='Đạt yêu cầu';
        }else if($ranking_value >=-10){
            $default_ranking ='Cần cố gắng';
        }else {
            $default_ranking ='Không đạt';
        }

        $viewer = $this->getViewer($request);
        $viewer->assign('DEFAULT_RANKING',$default_ranking);

        return parent::process($request); // TODO: Change the autogenerated stub
    }

    public function showModuleDetailView(Vtiger_Request $request) {

        $recordId = $request->get('record');
        $moduleName = $request->getModule();

        // Getting model to reuse it in parent
        if (!$this->record) {
            $this->record = Vtiger_DetailView_Model::getInstance($moduleName, $recordId);
        }
        $recordModel = $this->record->getRecord();
        $viewer = $this->getViewer($request);
        $viewer->assign('IMAGE_DETAILS', $recordModel->getImageDetails());

        return parent::showModuleDetailView($request);
    }
}