<?php
/**
 * Created by PhpStorm.
 * User: Netbase
 * Date: 4/23/2019
 * Time: 9:37 AM
 */


class Employee_Detail_View extends Accounts_Detail_View {


    public function checkPermission(Vtiger_Request $request)
    {
        $moduleName = $request->getModule();
        $recordId = $request->get('record');

        $canEdit = false;
        if($moduleName=='Employee'){
            $recordModel = Vtiger_Record_Model::getInstanceById($recordId,$moduleName);
            $smCreator = $recordModel->getCreatorId($recordId);
            if($smCreator == Users_Record_Model::getCurrentUserModel()->getId() || Users_Record_Model::getCurrentUserModel()->getUserRoleName()=='Vice President'){
                $canEdit = true;
            }
        }

        $recordPermission = Users_Privileges_Model::isPermitted($moduleName, 'DetailView', $recordId);
        if(!$recordPermission) {
            if(!$canEdit){
                throw new AppException(vtranslate('LBL_PERMISSION_DENIED'));
            }
        }

        if ($recordId) {
            $recordEntityName = getSalesEntityType($recordId);
            if ($recordEntityName !== $moduleName) {
                throw new AppException(vtranslate('LBL_PERMISSION_DENIED'));
            }
        }
        return true;
    }

    function __construct() {
        $this->exposeMethod('showModuleDetailView');
        parent::__construct();
    }

    function preProcess(Vtiger_Request $request, $display = true)
    {
        global $current_user, $adb;
        $recordId = $request->get('record');
        $sqlUser = "SELECT
                        user_id
                    FROM
                        vtiger_hrm_employee ve
                    INNER JOIN vtiger_crmentity vc ON vc.crmid = ve.employid
                    WHERE
                        vc.deleted = 0
                    AND ve.employid = ?";
        $resultUserId = $adb->pquery($sqlUser,array($recordId));
        $userId = $adb->query_result($resultUserId,'user_id',0);

        $viewer = $this->getViewer($request);
        $viewer->assign('USER_ID',$userId);
        $viewer->assign('IS_ADMIN',$current_user->is_admin);

        parent::preProcess($request, $display);
         // TODO: Change the autogenerated stub
    }

    function process(Vtiger_Request $request)
    {
        return parent::process($request); // TODO: Change the autogenerated stub
    }

    public function showModuleDetailView(Vtiger_Request $request) {

        $recordId = $request->get('record');
        $moduleName = $request->getModule();

        // Getting model to reuse it in parent
        if (!$this->record) {
            $this->record = Vtiger_DetailView_Model::getInstance($moduleName, $recordId);
        }
        $recordModel = $this->record->getRecord();
        $viewer = $this->getViewer($request);
        $viewer->assign('IMAGE_DETAILS', $recordModel->getImageDetails());

        return parent::showModuleDetailView($request);
    }
}